development:
  adapter: postgresql
  host: localhost
  database: teachbase_dev
  username: task2014
  password: 1

test:
  adapter: postgresql
  host: localhost
  database: teachbase_dev
  # username: task2014
  # password: 1

production:
  adapter: postgresql
  host: localhost
  database: teachbase
  # username: task2014
  # password: 1
